### ISSUE TITLE
ImportError: No module named attr

### ISSUE THREAD

**Issue by eimfach** [william-index/plantgod#1]
When starting the main.py following error occurs:

```
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from God import God
  File "/Users/robingruenke/Documents/workspaces/plantgod/God/__init__.py", line 1, in <module>
    from God import God
  File "/Users/robingruenke/Documents/workspaces/plantgod/God/God.py", line 1, in <module>
    import attr
ImportError: No module named attr
```

Using Python 2.7.10

**Comment by william-index** [comment]
You need to pip install it, meaning what I (or you need to do) is create a requirements.txt file for pip. Thanks for pointing this out.

**Comment by william-index** [comment]
@eimfach Just pushed the fix
`pip install -r requirements.txt`

https://github.com/william-index/plantgod/commit/6aa07ed2694a59659fe56fc95f2c5adf7757c498
